site_name: Developer Tools
site_url: https://rudmls.github.io/developer-tools/
site_author: Ruddy Monlouis
repo_url: https://github.com/rudmls/developer-tools

theme:
  name: material
  language: 'fr'
  favicon: img/favicon.ico
  features:
    - navigation.top
  palette:
    - scheme: default
      primary: teal
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: darkblue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  # - i18n:
  #     default_language: en
  #     languages:
  #       fr: Français
  #       en: English

markdown_extensions:
  - toc:
      toc_depth: 6
      permalink: True
  - codehilite
  - attr_list
  - codehilite
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Java:
    - Utiles : ./pages/java/utils.md
    - Gson: ./pages/java/gson.md
    - Agent Java: ./pages/java/java_agent.md
  - Linux: 
    - Utiles: ./pages/linux/utils.md
    - SSH: ./pages/linux/ssh.md
  - Docker:
    - Utiles: ./pages/docker/utils.md
    - Swarm: ./pages/docker/swarm.md
  - Hadoop: 
    - Installation sur WSL: ./pages/hadoop/install-wsl.md